### ISSUE TITLE
Segmentation Fault ./ytc add "way above the skyline"

### ISSUE THREAD

**Issue by leothelocust** [koekeishiya/ytc#1]
I'm trying to use this after installing it, ytd, and mpv, but i'm getting the following error.

`[1]    28002 segmentation fault  ./ytc add "way above the skyline"`

I'm sure I'm just searching wrong, or typing something wrong, but i've also tried the following:

```
./ytc add 'way above the skyline'
./ytc add way+above+the+skyline -index 3
./ytc add way+above+the+skyline 3
./ytc add "way+above+the+skyline" -i 3
etc...
```
and each time I get a segmentation fault.

Please help! Thanks in advance for this tool!

**Comment by koekeishiya** [comment]
Uh, you need a valid google (youtube) api key

https://github.com/koekeishiya/ytc/blob/master/ytc.cpp#L33

**Comment by leothelocust** [comment]
Oh of course! Thank you so much!

**Comment by leothelocust** [comment]
Hmm, that doesn't seem to fully fix my issue.

I have edited `ytc.cpp` like you suggested to include the youtube api key.

I have started the `ytd` daemon after creating a `~/.ytdrc` file that looks like the following:
```
mpv=/usr/local/bin/mpv
port=3001
daemon=on
video=off
repeat=on
fullscreen=off
```

The result of `which mpv`is: `/usr/local/bin/mpv`

and I had to change my PORT in https://github.com/koekeishiya/ytc/blob/master/ytc.cpp#L15

```
$  ./ytc add 'way above the skyline'
[1]    42983 segmentation fault  ./ytc add 'way above the skyline'
```
Any thoughts?

Thanks again!

**Comment by leothelocust** [comment]
I've verified the daemon is running:

```
$   ps aux | grep ytd
lolson          36908   0.0  0.0  2451316    444 s001  S    11:49AM   0:00.00 ./ytd
```

**Comment by koekeishiya** [comment]
>  ./ytc add 'way above the skyline'

should be called without the quotes:
`./ytc add way above the skyline`

**Comment by leothelocust** [comment]
SWEEET! That's what I needed. Thank you!
